### ISSUE TITLE
Add `continue` to the Ivory language

### ISSUE THREAD

**Issue by jameysharp** [GaloisInc/ivory#37]
It would be nice to be able to use C's `continue` statement in Ivory loops. We can use `if` statements spanning the end of the loop body to simulate this in common cases, but there are algorithms that are more clear if expressed using `continue`.

@elliottt and I discussed this and we don't think there are any difficulties. We would need to add a fourth type parameter to `Effects`, analogous to `BreakEff`, for `ContinueEff`.

**Comment by pchickey** [comment]
My personal feelings on this change is that non-local control statements like break, ret, and continue don't belong in the language at all, but since they are, there's no real harm in adding more.

Adding new AST nodes increases the complexity of backend tools. We should consider having these nonlocal operators desugar to ordinary `Ifte` branches in the AST. This will decrease complexity of the backends and make it easier to trust that backend tools are implemented correctly.

**Comment by Hodapp87** [comment]
I was going to ask about ```switch``` & ```case``` and possibly write a patch to implement them, but in light of what @pchickey just said, would big ```if```/```then``` ladders (which I'm using now) still be preferable?

**Comment by pchickey** [comment]
Hi Chris,
 
Great question!
 
I think it is best to implement control flow primitives as a library as much as possible, rather than building them into the language. When we do need to build primitives into the language, we should do so by implementing them as syntax, but not as part of the AST, whenever possible.
 
Non-local control syntax requires modifying statements outside of their own scope - this is desirable because it allows us to build really powerful additions to the language without changing the interface to any of the backends. The motivating example I have in mind here are the way Jamey used AST manipulations to implement `Ivory.Language.Coroutine`, which uses ordinary Ivory syntax and produces an ordinary Ivory AST. I can imagine implementing loop `break` and `continue`, and proc `ret`, using AST manipulations to convert that syntax to ordinary `Ifte` AST nodes, and then removing the existing `Break` and `Ret` nodes from the AST.
 
But back to the topic of local control flow: In `Ivory.Stdlib` we've defined `cond_` and `cond`, which you can use just like C `switch/case` but are also more powerful - for example, `cond` returns a monadic value.
 
In other cases, you may end up rolling your own control using `foldl` and the `(?)` operator, or `foldM` and `ifte_`, and so on, depending on your particular needs. I prefer to describe a computation with haskell terms wherever possible.
 
Unfortunately, we cannot use haskell `case` or other pattern matching operations to describe Ivory computations - that is a drawback of embedding in haskell and (I believe) still an open research problem. This is part of why we there is no particularly elegant way to define sum types in Ivory.
 
Pat

**Comment by Hodapp87** [comment]
@pchickey: Thank you - that's most helpful. I was using ```foldl``` and ```ifte_``` to accomplish basically a ```switch/case``` for mapping an ```IvoryIntegral``` to types that are in ```Enum``` and ```Bounded``` - but I was not aware of ```cond_``` until now. I need to do a better job reading the docs, clearly.

**Comment by pchickey** [comment]
Not your fault at all! Our docs are way less than satisfactory. It doesn't look like we mention `cond_` anywhere obvious in the docs.

**Comment by Hodapp87** [comment]
Oh, the Haddock docs for ```Ivory.Stdlib.Control``` seem to explain it.

**Comment by jameysharp** [comment]
Fold over ifte or (?) has unfortunate consequences for the performance of the generated code sometimes, and the stdlib cond functions can't optimize when there are better alternatives. So I've been meaning to add some stdlib functions for those special cases:

- If every case tests the same variable for equality against various Haskell-time integer constants, we can replace the linear time if-else ladder with either a log-time binary search, a constant-time jump table (although we can't express the latter in Ivory AST yet), or a hybrid. This is an optimization that C compilers apply to switch statements, but I think it's worthwhile for Ivory to give programmers more control over the asymptotic complexity and memory usage of their code.

- If, in addition, all of the right-hand sides are constant expressions, we may be able to generate a constMemArea lookup table for constant-time evaluation. That's currently easier to implement on a case by case basis, but it would be nice to be able to capture it in a library.

But that's a digression from the point of *this* issue, which is non-local control flow described by the continue statement. Transforming continue into ifte is non-trivial in general and requires similar AST to AST manipulation like I did for coroutines. I think it might lead to exponential blowup, even? If we decide we don't want continue in the AST, I don't think the alternative is worth implementing.

I also don't think this is high priority, so we don't have to decide right now. :-)

**Comment by leepike** [comment]
I'm closing this issue. We have not (and don't plan to) add `continue` to the language for the foreseeable future, for the reasons @pchickey described and given that we are targeting high-assurance systems.
