### ISSUE TITLE
Allow custom assert code

### ISSUE THREAD

**Issue by expipiplus1** [GaloisInc/ivory#41]
It would be nice to be able to replace the `ivory_assert` define with some custom functionality. For example at the moment we print the assert message to a serial console and sit flashing a led.

As far as I can tell this change could be as simple as checking if `ivory_assert` is already defined in [ivory_asserts.h](ivory/ivory-backend-c/runtime/ivory_asserts.h).

**Comment by pchickey** [comment]
Thanks for the bug report. You're right, our current method for dealing with assertions is pretty anti-modular, and we should be able to do a lot better.

I'll talk with the rest of the team about this on Monday, and we'll come up with something that works with all of our existing Ivory targets, and allows the user to pick a more flexible assertion implementation.

**Comment by leepike** [comment]
I think @expipiplus1's suggestion is completely reasonable. Are there any reasons not to?

**Comment by expipiplus1** [comment]
There may need to be a mechanism to put the users `ivory_assert` in scope everywhere.

**Comment by pchickey** [comment]
I'd prefer not to give the user arbitrary control of includes and macros in the Ivory runtime if we can avoid it. Here is a [proposed solution](https://github.com/GaloisInc/ivory/commit/de389d050b12f13f7c6f46b84a055fd04b3c3acf) which allows the user to provide an assertion hook as a library. I made this a bit flexible with a verbose user hook as an option. This is configurable because users might not have room for `__FILE__` and `__LINE__` constants on embedded systems with limited program size.

**Comment by expipiplus1** [comment]
Often it's nice to have the expression for `arg` as a string when printing asserts in addition to file and line.
Changing the line in the verbose definition for `ivory_assert` to `ivory_user_verbose_assert_hook(atype, #arg, __FILE__, __LINE__);`

**Comment by pchickey** [comment]
That suggestion sounds good to me. I'll merge this with master as soon as we work out what the assert hooks will be for each of our user's platforms.

**Comment by pchickey** [comment]
assert hooks are now in master. Thanks again for this bug report!
