### ISSUE TITLE
Separating procedure declaration and definition

### ISSUE THREAD

**Issue by Hodapp87** [GaloisInc/ivory#54]
I have written various Ivory procedures that are parametrized over something (say, a board definition or some other configuration), so I will have something like this:

```haskell
foo :: Bar -> Def ('[] :-> ())
foo bar = proc "foo_proc" $ body $ do ...
```

With ```call``` this can become a bit cumbersome because then every ```call``` to it must also be parametrized over ```Bar```, and every call to that recursively, up to the point where some ```Bar``` is actually known. In my own code, this can be a lot of repeated boilerplate at every level when I have multiple bits of board/build configuration filtering down from the top level of the build.

In ```foo``` above, the definition (in the C sense) may depend on the function parameters, but the declaration (again in the C sense) does not - the function signature cannot, and the function name does not. It seems to me that while ```incl``` requires the full definition, ```call``` requires only the declaration, and it should be independent of the function's implementation.

I have used a stopgap measure that keeps the proc type and name; something like:

```haskell
fooProto :: Def ('[] :-> ())
fooProto = importProc "fooProc" ""
```

This works, but it is a bit of a kludge (is it even kosher to give an empty header name?). It can also easily violate type-safety, should the procedure types between ```fooProc``` and ```fooProto``` drift apart.

I suppose what I'd like is the ability to do something like...

```haskell
foo :: Def ('[] :-> ())
foo = procDecl "fooProc"

fooImpl :: Bar -> Def ('[] :-> ())
fooImpl bar = procImpl fooProto $ body $ do ...
```
where ```fooProc``` will fail to type-check if the procedure types are mismatched, I can easily ```call``` to ```foo``` without worrying about ```Bar```, and I of course must produce a concrete definition via ```fooImpl``` in order to actually ```incl``` this function.

I may go try to implement this, but I'm interested in people's opinions first. Did I totally miss an existing obvious way in Ivory to do this? Does this still pose big concerns for safety or correctness?

**Comment by pchickey** [comment]
Hi Chris! This is a really good question. I'm glad to see that others have run into this weird corner of the language design as well. It presented a bunch of problems throughout the design and implementation of tower.

Unfortunately, we haven't come up with a satisfactory solution for every use case. We have, in the past, solved this problem by relying on a `call` on an ivory function is strict only on the function identifier (string argument to proc). 

So to re-use your example program

```
foo :: Bar -> Def ('[] :-> ())
foo bar = procImpl "some_constant_string" $ body $ do ...
```

The caller of `foo`, who may not have a `bar` argument available, can still generate valid code via `call_ (foo undefined)` or better yet `call_ (foo (error "broken invariant: call to foo should not be strict in the argument"))`. So you can export some variant of `foo` from the module.

Admittedly, this is ugly, because abusing strictness often makes code hard to read and reason about. But if you do so in a a principled way, perhaps you could implement your proposed `procDecl` and `procImpl` along these same lines as a library, rather than a modification to `ivory`, if you were willing to wrap (or replace) `Def` with another dataype (perhaps `ProtoDef`?), and make variants of of `call` and `incl` that do the correct thing.

As far as extending the Ivory language to include this concept, I don't have any specific objections to your proposal, but I'd defer to @elliottt and others to think on it further. While I totally understand the ways this is useful (and, in terms of C programming, even idiomatic) I'm a bit wary to add anything more to the language that can be implemented as a library.

**Comment by Hodapp87** [comment]
Pat, good to see I'm not alone in having this problem! By coincidence, I also ran into http://okmij.org/ftp/Haskell/tr-15-04.pdf and saw that my issue is probably 90% just a more specific form of the 'configurations problem'.

It looks like a library should be able to accomplish this. I can't see any reason why the AST needs some special representation of a function prototype.

I hadn't thought of relying on ```call``` being strict only on the name. Still, though, it seems like ```DefImport``` (as ```importProc``` creates) is a cleaner/safer representation, since one may examine the ```Def``` and just treat it like a procedure defined elsewhere, while ```DefProc``` adds a ```procBody``` field that must remain unevaluated.

That suggests one way - creating a function to turn a ```DefProc``` to a ```DefImport``` (and leaving body untouched), and extending this to handle functions of arbitrary arity that produce a ```Def``` by applying however many ```error ...```.

**Comment by pchickey** [comment]
Sounds good! I'll close this issue, but please re-open it if you discover any issues while implementing your library functionality.

**Comment by leepike** [comment]
@Hodapp87, why can't the issue be resolved as follows to elide the configuration parameter from the constant being `call`ed (`fooProxy`) while ensuring that the type of `fooProxy` must be consistent with the type of `foo`, with the configuration parameter?

```
data Bar = Bar { aField :: Int }

defaultBar :: Bar
defaultBar = Bar 0

foo :: Bar -> Def ('[Uint8] :-> ())
foo bar = proc "foo_proc" $ \_x -> body $ do retVoid

fooProxy :: Def ('[Uint8] :-> ())
fooProxy = foo defaultBar

caller :: Def ('[] :-> ())
caller = proc "caller" $ body $ call_ fooProxy 3
```

**Comment by Hodapp87** [comment]
@leepike, the way I see it, this just becomes the same thing if it's generalized to support arbitrary types. I will show you what I mean with a pull request once I've converted over what I did a few days ago and put it someplace appropriate in Ivory.
